version: '3.8'

services:
  app:
    build: .
    container_name: application
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:100401@db:3000/user_roles
    restart: always
    links:
      - db
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 100401
      POSTGRES_DB: user_roles
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always


volumes:
  postgres_data:

